# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inorm <- function(x) {
    .Call(`_GCGK_inorm`, x)
}

V <- function(a, b, c, d, s) {
    .Call(`_GCGK_V`, a, b, c, d, s)
}

GCGK <- function(X, parameters) {
    .Call(`_GCGK_GCGK`, X, parameters)
}

GCGKTEST <- function(X, parameters, iteration) {
    .Call(`_GCGK_GCGKTEST`, X, parameters, iteration)
}

